language: go

go:
  - 1.4
  - 1.5

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get github.com/cucumber/gherkin-go
  - go get github.com/stretchr/testify/assert
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

script:
    - $HOME/gopath/bin/goveralls -service=travis-ci
