// Code generated by "stringer -type=tokenKind"; DO NOT EDIT

package actor

import "fmt"

const _tokenKind_name = "token_commenttoken_tagtoken_actorDefinitiontoken_texttoken_goalstoken_goaltoken_empty"

var _tokenKind_index = [...]uint8{0, 13, 22, 43, 53, 64, 74, 85}

func (i tokenKind) String() string {
	if i < 0 || i >= tokenKind(len(_tokenKind_index)-1) {
		return fmt.Sprintf("tokenKind(%d)", i)
	}
	return _tokenKind_name[_tokenKind_index[i]:_tokenKind_index[i+1]]
}
